# Site settings
title:          My Blog
description:    "Welcome to My Blog"
url:            https://github.com/crownk12/crownk12.github.io/

# Author
author:
  name:         Wonkyun Yim
  email:        yimwk88@email.arizona.edu
  url:          https://crownk12.github.io/

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: yimwk88@email.arizona.edu
  github: https://github.com/crownk12
  twitter: 
  linkedin: 
